"""Resume card generator — portable proof of contribution.

A resume card is a one-page summary of what someone did on a project,
confirmed by their teammates. It contains:

  - Project context (what the team did)
  - What *this person* contributed (their claim)
  - Peer confirmation status (verified by teammates)
  - Categories of work they covered

The card is the *payoff* of the whole system. People tolerate being measured
if they get something valuable back — and a verified resume card is more
credible than a self-reported bullet point.

Output is Markdown (pasteable into LinkedIn, a portfolio, a resume, or
Notion). Future: PDF export.
"""

from __future__ import annotations

from typing import Dict, List


def generate(member_name: str, member_role: str, project_name: str,
             project_description: str, contributions: List,
             confirmations: List, all_members: List) -> str:
    """Generate a Markdown resume card for one person on one project."""

    # Confirmation lookup: contribution_id -> [statuses]
    confirm_map: Dict[str, List] = {}
    for cf in confirmations:
        confirm_map.setdefault(cf.contribution_id, []).append(cf)

    lines = [
        f"# Verified Project Card",
        "",
        f"**{member_name}**" + (f" — {member_role}" if member_role else ""),
        "",
        "---",
        "",
        f"## Project: {project_name}",
    ]
    if project_description:
        lines += [f"_{project_description}_", ""]

    team_names = [m.name for m in all_members]
    lines += [f"**Team:** {', '.join(team_names)}", ""]

    # Contributions
    lines += ["## What I did", ""]
    if not contributions:
        lines += ["_No contributions logged._", ""]
    else:
        for c in contributions:
            # Confirmation status for this contribution
            cfs = confirm_map.get(c.id, [])
            confirmed = sum(1 for cf in cfs if cf.status == "confirmed")
            adjusted = sum(1 for cf in cfs if cf.status == "adjusted")
            disputed = sum(1 for cf in cfs if cf.status == "disputed")
            pending = sum(1 for cf in cfs if cf.status == "pending")
            total_reviewers = len(cfs)

            if total_reviewers == 0:
                badge = "not yet reviewed"
            elif disputed > 0:
                badge = "disputed"
            elif adjusted > 0:
                badge = f"partly confirmed ({confirmed + adjusted}/{total_reviewers})"
            elif confirmed == total_reviewers:
                badge = f"verified by {confirmed} teammate(s)"
            else:
                badge = f"{confirmed}/{total_reviewers} confirmed"

            cat_tag = f" [{c.category}]" if c.category else ""
            lines.append(f"- **{c.title}**{cat_tag} — _{badge}_")
            if c.description:
                lines.append(f"  {c.description}")

    lines += [""]

    # Summary stats
    total_contribs = len(contributions)
    all_cfs = [cf for c in contributions for cf in confirm_map.get(c.id, [])]
    fully_verified = sum(
        1 for c in contributions
        if confirm_map.get(c.id) and
        all(cf.status == "confirmed" for cf in confirm_map[c.id])
    )
    categories = sorted(set(c.category for c in contributions if c.category))

    lines += [
        "## Summary",
        "",
        f"- **Contributions:** {total_contribs}",
        f"- **Fully verified:** {fully_verified} of {total_contribs}",
        f"- **Areas:** {', '.join(categories) if categories else 'not categorized'}",
        "",
        "---",
        "",
        "_This card was generated by Clearwork. Contributions are self-reported "
        "and peer-confirmed — each item shows its verification status._",
    ]

    return "\n".join(lines)
